local_costmap:
  #The global frame for the costmap to operate in
  global_frame: map

  #The name of the frame for the base link of the robot
  robot_base_frame: base_link

  #Specifies the delay in transform (tf) data that is tolerable in seconds.
  transform_tolerance: .2000

  update_frequency: 5.0 #50
  publish_frequency: 2.0

  static_map: false
  rolling_window: true

  width: 10
  height: 10
  resolution: 0.025

